import React from "react";
import {Metadata} from "next";

export const metadata: Metadata = {
    title: {
        template: '%s | CS-391',
        default: 'URL Shortener | CS-391',
    },
    description: 'Generated by create next app',
};

export default function RootLayout(
    {children,}:
    Readonly<{ children: React.ReactNode; }>
) {
    return (
        <html lang="en">
        <body style={{margin: 0, boxSizing: 'border-box'}}>
        {children}
        </body>
        </html>
    );
}
